#!/bin/sh
        cpu_temp="$(awk '{ printf("%.1f°C ", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)" #CPU温度
                if [ -e /sys/class/ieee80211/phy0/hwmon0/temp1_input ] ; then
                  wifi_temp1="$(awk '{ printf("%.1f°C", $0 / 1000) }' /sys/class/ieee80211/phy0/hwmon0/temp1_input)" #增加这行，获取2.4G WiFi温度。注：获取到的是整数，没有小数点
                  wifi_temp2="$(awk '{ printf("%.1f°C", $0 / 1000) }' /sys/class/ieee80211/phy1/hwmon1/temp1_input)" #增加这行，获取5G WiFi温度。
                  echo -n "CPU:${cpu_temp}, 2.4G:${wifi_temp1}, 5G:${wifi_temp2}"
                else
                  echo -n "CPU:${cpu_temp}"
                fi
